export const Genres: string[] = [
  "Adventure",
  "Arcade",
  "Card & Board Game",
  "Fighting",
  "Hack and slash/Beat 'em up",
  "Indie",
  "MOBA",
  "Music",
  "Pinball",
  "Platform",
  "Point-and-click",
  "Puzzle",
  "Quiz/Trivia",
  "Racing",
  "Real Time Strategy (RTS)",
  "Role-playing (RPG)",
  "Shooter",
  "Simulator",
  "Sport",
  "Strategy",
  "Tactical",
  "Turn-based strategy (TBS)",
  "Visual Novel",
] as const;

export const GameFeatures = [
  "Singleplayer",
  "Multiplayer",
  "Coop",
  "Online Coop",
  "Split Screen",
  "Cross Platform Multiplayer",
];

export const UserRoleTable = [
  { value: "USER", label: "User" },
  { value: "MEMBER", label: "Member" },
  { value: "LEADER", label: "Leader" },
  { value: "ADMIN", label: "Admin" },
];

export const GenresTable = [
  { value: "Adventure", label: "Adventure" },
  { value: "Arcade", label: "Arcade" },
  { value: "Card & Board Game", label: "Card & Board Game" },
  { value: "Fighting", label: "Fighting" },
  { value: "Hack and slash/Beat 'em up", label: "Hack and slash/Beat 'em up" },
  { value: "Indie", label: "Indie" },
  { value: "MOBA", label: "MOBA" },
  { value: "Music", label: "Music" },
  { value: "Pinball", label: "Pinball" },
  { value: "Platform", label: "Platform" },
  { value: "Point-and-click", label: "Point-and-click" },
  { value: "Puzzle", label: "Puzzle" },
  { value: "Quiz/Trivia", label: "Quiz/Trivia" },
  { value: "Racing", label: "Racing" },
  { value: "Real Time Strategy (RTS)", label: "Real Time Strategy (RTS)" },
  { value: "Role-playing (RPG)", label: "Role-playing (RPG)" },
  { value: "Shooter", label: "Shooter" },
  { value: "Simulator", label: "Simulator" },
  { value: "Sport", label: "Sport" },
  { value: "Strategy", label: "Strategy" },
  { value: "Tactical", label: "Tactical" },
  { value: "Turn-based strategy (TBS)", label: "Turn-based strategy (TBS)" },
  { value: "Visual Novel", label: "Visual Novel" },
];

export const GameFeaturesTable = [
  { value: "Singleplayer", label: "Singleplayer" },
  { value: "Multiplayer", label: "Multiplayer" },
  { value: "Coop", label: "Coop" },
  { value: "Online Coop", label: "Online Coop" },
  { value: "Split Screen", label: "Split Screen" },
  { value: "Cross Platform Multiplayer", label: "Cross Platform Multiplayer" },
];

export const releaseYears = [
  { value: "2001", label: "2001" },
  { value: "2002", label: "2002" },
  { value: "2003", label: "2003" },
  { value: "2004", label: "2004" },
  { value: "2005", label: "2005" },
  { value: "2006", label: "2006" },
  { value: "2007", label: "2007" },
  { value: "2008", label: "2008" },
  { value: "2009", label: "2009" },
  { value: "2010", label: "2010" },
  { value: "2011", label: "2011" },
  { value: "2012", label: "2012" },
  { value: "2013", label: "2013" },
  { value: "2014", label: "2014" },
  { value: "2015", label: "2015" },
  { value: "2016", label: "2016" },
  { value: "2017", label: "2017" },
  { value: "2018", label: "2018" },
  { value: "2019", label: "2019" },
  { value: "2020", label: "2020" },
  { value: "2021", label: "2021" },
  { value: "2022", label: "2022" },
  { value: "2023", label: "2023" },
  { value: "2024", label: "2024" },
  { value: "2025", label: "2025" },
  { value: "2026", label: "2026" },
];
